apiVersion: v1
baseDomain: azsdps.labbuildr.com
imageContentSources:
- mirrors:
  - harbor.pks.home.labbuildr.com/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - harbor.pks.home.labbuildr.com/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
credentialsMode: Manual
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFZDCCA0ygAwIBAgIQRN6G0euYuadGPYZv2m9tvjANBgkqhkiG9w0BAQsFADAn
  MSUwIwYDVQQDDBxBenVyZVN0YWNrU2VsZlNpZ25lZFJvb3RDZXJ0MB4XDTIyMDcy
  NzE2MDQwNVoXDTIzMDcyNzE2MjQwNVowJzElMCMGA1UEAwwcQXp1cmVTdGFja1Nl
  bGZTaWduZWRSb290Q2VydDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
  AKu/hw6sU1v5foF8hN8/RAtdk0TRyVokyU5i+BGug+kZUHU08Dok/jcO6Nis36hM
  qFE17V/BhKn3JCDjJlViCWbWhg+r67j6GPJJVzyfDe7xeL+Ky8yA78bACV59Q7fN
  +zrM8z6fWqpGkwfVwbH8w6kGLsWU1xCj1cZT7vfPNAtsshgDg5hiAauliD7QR5h5
  8VRcG0yuU/sus90cMOxfbbMDsJfBFeSSMkHq83/brE9AsD/u/RbsoRYZXGNXr2C8
  QeGyuX7BbP3yhcNbbaqKeasHGpIQ1+dk8gdTEP0ilIGQy7LQ3vjOY/EWVySPBVyJ
  G9ZMWrauAydB14aTYJ/pEI9s/Vu8EOIAjXyMktXYV6aIxNzf+mJfT9YIxyaND5b8
  r7HRHrFood1aGF0M1cKuIc15eV0rxkN2kRJpYMupmdJrDgs85dWrRRtKOy+weFff
  t1QxFh+bvJK1vXSkqqZIqQkYeDbqoXxMXQ+eIVPbEgC0yxaT1DuGNHrWxYH+EMtQ
  SoIlHWKlUZMuFb7rqFsaKMaJUx5bKBj9sdCMlh7nY5krpVneDEEQ9X2384flPbyA
  BhP3F2Qq3j2xcjdCA9nMn0IUWBeH0Ci/ma/0bbwqtS1ZdVPjJcYHQulDhirnmDWY
  luTzP5OS7b5zql3DTbt50Q2z1vLHx3W/ab09BJoFGzHFAgMBAAGjgYswgYgwDgYD
  VR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAkBgNV
  HREEHTAbghlsb2NhbC5henVyZXN0YWNrLmV4dGVybmFsMBIGA1UdEwEB/wQIMAYB
  Af8CAQMwHQYDVR0OBBYEFJDkHQfCnMQ0yWOE/EhFT2x7zYjLMA0GCSqGSIb3DQEB
  CwUAA4ICAQBWtNvnFeERRmLFCU+C9nzhN8W0sBpl0yuw3vW7bU2/92O0Dujr4/Ym
  uhHPEoWgzDGzll6PJA23MLbAaVeLd9qbQfRuemdp5E+pUeTY9zuN45t+OmD0Uz6G
  sVMcdNtPU7TNQTn9Rt35sWBalZj/WLuFv8P768GpqGqPOb0kUevf0Cy3xIO5mcv9
  1Qc5BzpmK05US4xv9/1QUFOtGAXstmI50wJhCSp+Ucn0ocy1nk4dcFcaWeGvShJX
  C3uGqcVldGN0DeRozfj3C09teKJ61MvodzkCzh1LgP6r9fksn0Gpg0kitPSj1PZG
  XP41/gYwfowA4AZ6PBRVnAo5vS80iQLaMb/ZwZRcNuR+qU2e/sboRmdczLU9LVZT
  fiYjZjILFdxJ5LxVqD059X0lX3G4h9Zcg/INxjMQ216J7Y/vYDqmCdmnT71iqFrJ
  a1y3H0wLB1pnGMDsauxWZhr4Iq3yj5s23B9s22ct6RoWeH6NQ/tCCv8Nw09O9wk5
  dfTaDb97kyZbh8pTXuDJ2NKcA1tmoOjkNAidaho8wzC9zMTWD7qjuJ/nTD1shhZi
  dPs+N7v+A4EmiTrc3yp99NpBAU6QlhOTmh28enwCzC8/zEIIb6OFZCkLQ1zqP4kC
  procl1IjrNiulgoQnkUgzkJ0M7YUbjSrIbgYao3stkbTgL+UlkHGeA==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
  TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
  cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
  WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
  RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
  AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
  R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
  sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
  NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
  Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
  /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
  AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
  Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
  FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
  AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
  Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
  gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
  PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
  ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
  CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
  lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
  avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
  yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
  yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
  hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
  HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
  MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
  nLRbwHOoq7hHwg==
  -----END CERTIFICATE-----
controlPlane: 
  name: master
  replicas: 3
compute: 
- name: worker
  hyperthreading: Enabled
  platform: {}
  replicas: 3
metadata:
  name: ocpcluster1 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    armEndpoint: https://management.local.azurestack.external
    baseDomainResourceGroupName: dns 
    region: local 
    outboundType: Loadbalancer
    cloudName: AzureStackCloud
    clusterOSImage: https://opsmanagerimage.blob.local.azurestack.external/images/rhcos-411.86.202207150124-0-azurestack.x86_64.vhd
# pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTc0ZTJmNzYxNjI5NDE2ODgzNWI3Mzc2MzFiMzAzNDA6UTlaSFI4QVNTQUE1UEpXUUVBWTRDSjMyTkFWM1lCUlFXVkJPT1VXOUhDR05XTEQ0S0xUUElSR09NVzRDN1ZNRg==","email":"karsten.bott@dell.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTc0ZTJmNzYxNjI5NDE2ODgzNWI3Mzc2MzFiMzAzNDA6UTlaSFI4QVNTQUE1UEpXUUVBWTRDSjMyTkFWM1lCUlFXVkJPT1VXOUhDR05XTEQ0S0xUUElSR09NVzRDN1ZNRg==","email":"karsten.bott@dell.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWE5MTA0ZjE5LTdmMWEtNGUxMy1iNzA3LTVjYjZmODYzZmRjNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPV1kwTVRneE56QmxPVEkwTVRGaFlXWTRNV1k1WldaaVlXVTNaVFk1TkNKOS5TeXBNVDIwOFdQQ0w5bUxyOXlFeWotNU9BcC1lWDl4b1hFNkpfMi1vT1owRnUtdldVQ2l5VmZNNlVSVUlmcjlIRjRHVXZqTTZNV0NKdFlKcEV4LTJGTkVJYzNnYlN1YmNCaC0wbmJEMERZcGJvbDVMZkdYODdJR01OLU9xSHpyR1k3Q3RuZnhnUTM3dVd0LVQxaDdQUHVBSkh0TkNyWk5ETDZHbFNUMno1UHQ5djlvbEZqN2N1X2oxNmpXN0RNLXo5dmpQZkVtaW1YcUlOaXdraUo2cnNmRFBHaXd4dTN2aFhpVUVZM2tRaGZCckczazRSQWp3SUJrNHRvWE91dzdHbWRoWF91LXByY1psakNSOHNlZ2JOTV9mc29VM2VoSWZaZTFmTm1QdHBUTy1DR3BKODlTSzltSTVsV3JRZzBJU1FmWlV4TUZwNHJqWFJ5ekFES0VOT3Z0eDdOSmJ2anlpNTAwRnN1cTUtMlVkRlFDdE5CNmxUUGllUjVWdGJfYm9DY2UwWXQ3Sk9wXy1xWjZMWVRkMEVKd1M4bE9rcG5yWmMxYS1oa0owUFZPbHg4cVVwRE5LUUJjSmo3d3ZtWGNHTk5BNkxybFNiMEFzeGxPd0xSUzR2a0RIX2lWVy1icHdsQ0NzNFRhaldwUnNLczZEWWpkNzhxLUFvMnFwYmp5WXk0Tm1UMXFONmdKZldFb1poVHNBQkhILXBWaFpMZ2tZc3BIaHh1SVZfeWVUcEJpSXh0VnIyVEcwb3AxUEZZYXFHdDRaeWFEbWwxTmhkSHVFY21tQUJTai1xT0tZVzFDNzBDWEtPSzdRMDVnT295TWdwS3hWM2ZCRTZWLUV4cGlnMHQ0UU5kVll4djhOcmpPdWV0V0FuSTRlNHRncndfMVF5VThONVZhV2JsVQ==","email":"karsten.bott@dell.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWE5MTA0ZjE5LTdmMWEtNGUxMy1iNzA3LTVjYjZmODYzZmRjNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPV1kwTVRneE56QmxPVEkwTVRGaFlXWTRNV1k1WldaaVlXVTNaVFk1TkNKOS5TeXBNVDIwOFdQQ0w5bUxyOXlFeWotNU9BcC1lWDl4b1hFNkpfMi1vT1owRnUtdldVQ2l5VmZNNlVSVUlmcjlIRjRHVXZqTTZNV0NKdFlKcEV4LTJGTkVJYzNnYlN1YmNCaC0wbmJEMERZcGJvbDVMZkdYODdJR01OLU9xSHpyR1k3Q3RuZnhnUTM3dVd0LVQxaDdQUHVBSkh0TkNyWk5ETDZHbFNUMno1UHQ5djlvbEZqN2N1X2oxNmpXN0RNLXo5dmpQZkVtaW1YcUlOaXdraUo2cnNmRFBHaXd4dTN2aFhpVUVZM2tRaGZCckczazRSQWp3SUJrNHRvWE91dzdHbWRoWF91LXByY1psakNSOHNlZ2JOTV9mc29VM2VoSWZaZTFmTm1QdHBUTy1DR3BKODlTSzltSTVsV3JRZzBJU1FmWlV4TUZwNHJqWFJ5ekFES0VOT3Z0eDdOSmJ2anlpNTAwRnN1cTUtMlVkRlFDdE5CNmxUUGllUjVWdGJfYm9DY2UwWXQ3Sk9wXy1xWjZMWVRkMEVKd1M4bE9rcG5yWmMxYS1oa0owUFZPbHg4cVVwRE5LUUJjSmo3d3ZtWGNHTk5BNkxybFNiMEFzeGxPd0xSUzR2a0RIX2lWVy1icHdsQ0NzNFRhaldwUnNLczZEWWpkNzhxLUFvMnFwYmp5WXk0Tm1UMXFONmdKZldFb1poVHNBQkhILXBWaFpMZ2tZc3BIaHh1SVZfeWVUcEJpSXh0VnIyVEcwb3AxUEZZYXFHdDRaeWFEbWwxTmhkSHVFY21tQUJTai1xT0tZVzFDNzBDWEtPSzdRMDVnT295TWdwS3hWM2ZCRTZWLUV4cGlnMHQ0UU5kVll4djhOcmpPdWV0V0FuSTRlNHRncndfMVF5VThONVZhV2JsVQ==","email":"karsten.bott@dell.com"}}}' 
pullSecret: '{"auths":{"harbor.pks.home.labbuildr.com": {"auth": "YWRtaW46QnJlZGExMjA4","email": "admin@labbuildr.com"}}}'
fips: false 
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs8XlXTAzIBEVY9M6GtXNpVT01vcy2t0i4m2rvC0Qr7UgBywCngz9FsXljtia25IDEOxTkezVSsmNX4YxxppP00JWW+R//KmYp9zY7twIZJBOVUyVkTFNLscNRFM59O1BGOrWeR1qKOzSEQyhlCFnvUFGlXrIkumH+EBTwdK9QVqAwDwKhhfCmzYBzsQTwDcH2JgLya7z5Q0kw/DnmLDrnuBdber5wU0oPjFwX30YozDlIWwT/e2y5uQuKu8KpRacr6xu/CVPVNchjDrSV8reXXIBlswVCzgWuYm6tCVn/lwfMHRRpigG99asfELn69VD2VXeo8n37WGOO9fYU9s5PKmrwRHCwyQPQIPnioxghbvp794Cq8UvN73cEmAHg732bNtf0mB2lKAR9sL1iTY4aQFkiuRLT50g49uGK7hJGxDcXNSNN/YNlumD+OQC5AiCLp4bK0ogSRmdWqQXgMdUPG0GQRwxz309vkkWblyi7NTGA46RaCO0KxDrkCVPlPPk= karsten.bott@bottnet.de_macbook_air