apiVersion: v1
baseDomain: azsdps.labbuildr.com
publish: External
imageContentSources:
- mirrors:
  - harbor.pks.home.labbuildr.com/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - harbor.pks.home.labbuildr.com/ocp4/openshift4
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
credentialsMode: Manual
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFZDCCA0ygAwIBAgIQdYHOt2Bz5bRLrwRgD9gscDANBgkqhkiG9w0BAQsFADAn
  MSUwIwYDVQQDDBxBenVyZVN0YWNrU2VsZlNpZ25lZFJvb3RDZXJ0MB4XDTIzMDEz
  MDEwMjE0M1oXDTI0MDEzMDEwNDE0M1owJzElMCMGA1UEAwwcQXp1cmVTdGFja1Nl
  bGZTaWduZWRSb290Q2VydDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
  AN5Yr77QIMsJ9fbfuN/KHShDWRnHIuhcKYdm0gkXkEV8VNim26aniaScjOWcjA20
  JfTb2gu0tWopIzqyC/TkY8QEnXa11tNMDCo6uWvZZB6FFW7EtsN5WdEbfkHSeF3y
  j+h6FKrcsyJgKRSFns/1oeAKDiRnYHLNnTRuaFoQXGTqrz8YSCSGRJU898hGdKhW
  xGIe43E5WM2p9WkqCSbBCP3oOXF7TFPL1vEyY6beU1kFB9YpLFAtSI+SPJeTCoAI
  LIpQARJGL267yMS+HG9P2oi5drE0V1Q06Uq2Bn8e+qgZyUSXStO27qbC28rg/M6C
  kGCkg96NKVPfy47yNjHQg00TTIWrcoqvX47OYrHgR20rTGxz8vqTQuSFv0JNI88Z
  zRoeOktwuLMfXFZhzXGho6Y6TabXwUAghwC+CeLTtOLXzv8eOeZnYFAT1Iu/suSr
  fGNg6LnBGDO36DC/NBcC87eeeD5V2ucrMeiPTXD4pg77p65YDbFKRj7aO92cZIvV
  BoARpjxanPDKUBZR77CfZq6o3FBVaRvCRvVJ4RqFAk9Qg5v/8ka3Nrsd306sCoqP
  OGMDMbvfveyhxHzfHRnGQtNf0H9UyHvA7a6/TxP7PXBWNF+n35JFXCk9mLCds3/9
  q/318C+N+zab4t1ylhQliIe0J55aAdhWjP/OqGRfN1NZAgMBAAGjgYswgYgwDgYD
  VR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAkBgNV
  HREEHTAbghlsb2NhbC5henVyZXN0YWNrLmV4dGVybmFsMBIGA1UdEwEB/wQIMAYB
  Af8CAQMwHQYDVR0OBBYEFP7RqrUudC2kz+I1wo9lDBcMMaFlMA0GCSqGSIb3DQEB
  CwUAA4ICAQCjVlsEvSVOMJqalPvWMkfCDxc2R8oYLek0Du+GLI+Uu1jaWPWsNBPy
  4YS3WrpJ31XQJ3CHmF8/hYiBb8iwLAVkGz4xgyY6lzUh6g3CGqllMTLK63XcE5SA
  CWFhsOUOqNgFEODW59jV9lYNhfjd+D+hDQZsgqWmUatgpi914Ph+mQR4/3HShj6h
  wQcjkvpJO+I4966QkuWj3+urFgBLpBDzVVs0/UKc+26dwL8YQQSMSJ+xR02j8i0F
  ZAqJNZCVOdUumANVFAoHN0pZ7k08UuDY1zVHxDiYa68eI22lZjmzaWtIHbGY0MxJ
  ojcpAQxyVGr0umrV177baA0gE3tX+oHEMQXME3CDvv8OzvnJ98rrsEfStbfIkbFN
  t1b3hkiklcxz9jerB0/+FAYizKOuDHur/hznSZz7/zuhBksGnLrZo2HYCMjBGW3p
  18pTKrjpY2FQ1dMC8az9FfVoqKaOl/M4r5UM/6GCTpq+JC4UjH0x4E44oDU9iB5W
  iVrx9TP2rsV51Y9+ld2+djpFNZHZ72XVLwgr1fajgpCqrS+omhpkon+LnMxjSb+M
  bw7iN5rRlAq+saCnhbk2EOms5vJ7UMi2RuveGCg2ArCR7OSsN0icdOjt8gQMPuyg
  qM/kWh/T4X7iMRpaxWLWej+tICPbSIxvOjRGFzvgaGjvE5oPnWWDkw==
  -----END CERTIFICATE-----
  -----BEGIN CERTIFICATE-----
  MIIFFjCCAv6gAwIBAgIRAJErCErPDBinU/bWLiWnX1owDQYJKoZIhvcNAQELBQAw
  TzELMAkGA1UEBhMCVVMxKTAnBgNVBAoTIEludGVybmV0IFNlY3VyaXR5IFJlc2Vh
  cmNoIEdyb3VwMRUwEwYDVQQDEwxJU1JHIFJvb3QgWDEwHhcNMjAwOTA0MDAwMDAw
  WhcNMjUwOTE1MTYwMDAwWjAyMQswCQYDVQQGEwJVUzEWMBQGA1UEChMNTGV0J3Mg
  RW5jcnlwdDELMAkGA1UEAxMCUjMwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEK
  AoIBAQC7AhUozPaglNMPEuyNVZLD+ILxmaZ6QoinXSaqtSu5xUyxr45r+XXIo9cP
  R5QUVTVXjJ6oojkZ9YI8QqlObvU7wy7bjcCwXPNZOOftz2nwWgsbvsCUJCWH+jdx
  sxPnHKzhm+/b5DtFUkWWqcFTzjTIUu61ru2P3mBw4qVUq7ZtDpelQDRrK9O8Zutm
  NHz6a4uPVymZ+DAXXbpyb/uBxa3Shlg9F8fnCbvxK/eG3MHacV3URuPMrSXBiLxg
  Z3Vms/EY96Jc5lP/Ooi2R6X/ExjqmAl3P51T+c8B5fWmcBcUr2Ok/5mzk53cU6cG
  /kiFHaFpriV1uxPMUgP17VGhi9sVAgMBAAGjggEIMIIBBDAOBgNVHQ8BAf8EBAMC
  AYYwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwMBMBIGA1UdEwEB/wQIMAYB
  Af8CAQAwHQYDVR0OBBYEFBQusxe3WFbLrlAJQOYfr52LFMLGMB8GA1UdIwQYMBaA
  FHm0WeZ7tuXkAXOACIjIGlj26ZtuMDIGCCsGAQUFBwEBBCYwJDAiBggrBgEFBQcw
  AoYWaHR0cDovL3gxLmkubGVuY3Iub3JnLzAnBgNVHR8EIDAeMBygGqAYhhZodHRw
  Oi8veDEuYy5sZW5jci5vcmcvMCIGA1UdIAQbMBkwCAYGZ4EMAQIBMA0GCysGAQQB
  gt8TAQEBMA0GCSqGSIb3DQEBCwUAA4ICAQCFyk5HPqP3hUSFvNVneLKYY611TR6W
  PTNlclQtgaDqw+34IL9fzLdwALduO/ZelN7kIJ+m74uyA+eitRY8kc607TkC53wl
  ikfmZW4/RvTZ8M6UK+5UzhK8jCdLuMGYL6KvzXGRSgi3yLgjewQtCPkIVz6D2QQz
  CkcheAmCJ8MqyJu5zlzyZMjAvnnAT45tRAxekrsu94sQ4egdRCnbWSDtY7kh+BIm
  lJNXoB1lBMEKIq4QDUOXoRgffuDghje1WrG9ML+Hbisq/yFOGwXD9RiX8F6sw6W4
  avAuvDszue5L3sz85K+EC4Y/wFVDNvZo4TYXao6Z0f+lQKc0t8DQYzk1OXVu8rp2
  yJMC6alLbBfODALZvYH7n7do1AZls4I9d1P4jnkDrQoxB3UqQ9hVl3LEKQ73xF1O
  yK5GhDDX8oVfGKF5u+decIsH4YaTw7mP3GFxJSqv3+0lUFJoi5Lc5da149p90Ids
  hCExroL1+7mryIkXPeFM5TgO9r0rvZaBFOvV2z0gp35Z0+L4WPlbuEjN/lxPFin+
  HlUjr8gRsI3qfJOQFy/9rKIJR0Y/8Omwt/8oTWgy1mdeHmmjk7j1nYsvC9JSQ6Zv
  MldlTTKB3zhThV1+XWYp6rjd5JW1zbVWEkLNxE7GJThEUG3szgBVGP7pSWTUTsqX
  nLRbwHOoq7hHwg==
  -----END CERTIFICATE-----
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    azure:
      osDisk:
        diskSizeGB: 1024
      type: Standard_DS4_v2
  replicas: 3
compute: 
- name: worker
  architecture: amd64
  hyperthreading: Enabled
  platform:
    azure:
      osDisk:
        diskSizeGB: 1024
      type: Standard_DS4_v2
  replicas: 3
metadata:
  name: ocpcluster1
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  azure:
    armEndpoint: https://management.local.azurestack.external
    baseDomainResourceGroupName: dns 
    region: local 
    outboundType: Loadbalancer
    cloudName: AzureStackCloud
    clusterOSImage: https://opsmanagerimage.blob.local.azurestack.external/images/rhcos-410.84.202201251210-0-azurestack.x86_64.vhd
# pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTc0ZTJmNzYxNjI5NDE2ODgzNWI3Mzc2MzFiMzAzNDA6UTlaSFI4QVNTQUE1UEpXUUVBWTRDSjMyTkFWM1lCUlFXVkJPT1VXOUhDR05XTEQ0S0xUUElSR09NVzRDN1ZNRg==","email":"karsten.bott@dell.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfZTc0ZTJmNzYxNjI5NDE2ODgzNWI3Mzc2MzFiMzAzNDA6UTlaSFI4QVNTQUE1UEpXUUVBWTRDSjMyTkFWM1lCUlFXVkJPT1VXOUhDR05XTEQ0S0xUUElSR09NVzRDN1ZNRg==","email":"karsten.bott@dell.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWE5MTA0ZjE5LTdmMWEtNGUxMy1iNzA3LTVjYjZmODYzZmRjNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPV1kwTVRneE56QmxPVEkwTVRGaFlXWTRNV1k1WldaaVlXVTNaVFk1TkNKOS5TeXBNVDIwOFdQQ0w5bUxyOXlFeWotNU9BcC1lWDl4b1hFNkpfMi1vT1owRnUtdldVQ2l5VmZNNlVSVUlmcjlIRjRHVXZqTTZNV0NKdFlKcEV4LTJGTkVJYzNnYlN1YmNCaC0wbmJEMERZcGJvbDVMZkdYODdJR01OLU9xSHpyR1k3Q3RuZnhnUTM3dVd0LVQxaDdQUHVBSkh0TkNyWk5ETDZHbFNUMno1UHQ5djlvbEZqN2N1X2oxNmpXN0RNLXo5dmpQZkVtaW1YcUlOaXdraUo2cnNmRFBHaXd4dTN2aFhpVUVZM2tRaGZCckczazRSQWp3SUJrNHRvWE91dzdHbWRoWF91LXByY1psakNSOHNlZ2JOTV9mc29VM2VoSWZaZTFmTm1QdHBUTy1DR3BKODlTSzltSTVsV3JRZzBJU1FmWlV4TUZwNHJqWFJ5ekFES0VOT3Z0eDdOSmJ2anlpNTAwRnN1cTUtMlVkRlFDdE5CNmxUUGllUjVWdGJfYm9DY2UwWXQ3Sk9wXy1xWjZMWVRkMEVKd1M4bE9rcG5yWmMxYS1oa0owUFZPbHg4cVVwRE5LUUJjSmo3d3ZtWGNHTk5BNkxybFNiMEFzeGxPd0xSUzR2a0RIX2lWVy1icHdsQ0NzNFRhaldwUnNLczZEWWpkNzhxLUFvMnFwYmp5WXk0Tm1UMXFONmdKZldFb1poVHNBQkhILXBWaFpMZ2tZc3BIaHh1SVZfeWVUcEJpSXh0VnIyVEcwb3AxUEZZYXFHdDRaeWFEbWwxTmhkSHVFY21tQUJTai1xT0tZVzFDNzBDWEtPSzdRMDVnT295TWdwS3hWM2ZCRTZWLUV4cGlnMHQ0UU5kVll4djhOcmpPdWV0V0FuSTRlNHRncndfMVF5VThONVZhV2JsVQ==","email":"karsten.bott@dell.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWE5MTA0ZjE5LTdmMWEtNGUxMy1iNzA3LTVjYjZmODYzZmRjNzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPV1kwTVRneE56QmxPVEkwTVRGaFlXWTRNV1k1WldaaVlXVTNaVFk1TkNKOS5TeXBNVDIwOFdQQ0w5bUxyOXlFeWotNU9BcC1lWDl4b1hFNkpfMi1vT1owRnUtdldVQ2l5VmZNNlVSVUlmcjlIRjRHVXZqTTZNV0NKdFlKcEV4LTJGTkVJYzNnYlN1YmNCaC0wbmJEMERZcGJvbDVMZkdYODdJR01OLU9xSHpyR1k3Q3RuZnhnUTM3dVd0LVQxaDdQUHVBSkh0TkNyWk5ETDZHbFNUMno1UHQ5djlvbEZqN2N1X2oxNmpXN0RNLXo5dmpQZkVtaW1YcUlOaXdraUo2cnNmRFBHaXd4dTN2aFhpVUVZM2tRaGZCckczazRSQWp3SUJrNHRvWE91dzdHbWRoWF91LXByY1psakNSOHNlZ2JOTV9mc29VM2VoSWZaZTFmTm1QdHBUTy1DR3BKODlTSzltSTVsV3JRZzBJU1FmWlV4TUZwNHJqWFJ5ekFES0VOT3Z0eDdOSmJ2anlpNTAwRnN1cTUtMlVkRlFDdE5CNmxUUGllUjVWdGJfYm9DY2UwWXQ3Sk9wXy1xWjZMWVRkMEVKd1M4bE9rcG5yWmMxYS1oa0owUFZPbHg4cVVwRE5LUUJjSmo3d3ZtWGNHTk5BNkxybFNiMEFzeGxPd0xSUzR2a0RIX2lWVy1icHdsQ0NzNFRhaldwUnNLczZEWWpkNzhxLUFvMnFwYmp5WXk0Tm1UMXFONmdKZldFb1poVHNBQkhILXBWaFpMZ2tZc3BIaHh1SVZfeWVUcEJpSXh0VnIyVEcwb3AxUEZZYXFHdDRaeWFEbWwxTmhkSHVFY21tQUJTai1xT0tZVzFDNzBDWEtPSzdRMDVnT295TWdwS3hWM2ZCRTZWLUV4cGlnMHQ0UU5kVll4djhOcmpPdWV0V0FuSTRlNHRncndfMVF5VThONVZhV2JsVQ==","email":"karsten.bott@dell.com"}}}' 
pullSecret: '{"auths":{"harbor.pks.home.labbuildr.com": {"auth": "YWRtaW46QnJlZGExMjA4","email": "admin@labbuildr.com"}}}'
fips: false 
sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCs8XlXTAzIBEVY9M6GtXNpVT01vcy2t0i4m2rvC0Qr7UgBywCngz9FsXljtia25IDEOxTkezVSsmNX4YxxppP00JWW+R//KmYp9zY7twIZJBOVUyVkTFNLscNRFM59O1BGOrWeR1qKOzSEQyhlCFnvUFGlXrIkumH+EBTwdK9QVqAwDwKhhfCmzYBzsQTwDcH2JgLya7z5Q0kw/DnmLDrnuBdber5wU0oPjFwX30YozDlIWwT/e2y5uQuKu8KpRacr6xu/CVPVNchjDrSV8reXXIBlswVCzgWuYm6tCVn/lwfMHRRpigG99asfELn69VD2VXeo8n37WGOO9fYU9s5PKmrwRHCwyQPQIPnioxghbvp794Cq8UvN73cEmAHg732bNtf0mB2lKAR9sL1iTY4aQFkiuRLT50g49uGK7hJGxDcXNSNN/YNlumD+OQC5AiCLp4bK0ogSRmdWqQXgMdUPG0GQRwxz309vkkWblyi7NTGA46RaCO0KxDrkCVPlPPk= karsten.bott@bottnet.de_macbook_air